#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/a081de5/charts/library/common/values.yaml
#

controllers:
  main:
    type: statefulset
    # -- Enable devices to be discoverable
    hostNetwork: false
    containers:
      main:
        image:
          repository: ghcr.io/home-assistant/home-assistant
          pullPolicy: IfNotPresent
          tag: 2024.1.3
        # codeserver:
        #   dependsOn: main
        #   image:
        #     repository: ghcr.io/coder/code-server
        #     pullPolicy: IfNotPresent
        #     tag: 4.20.0
        #   enabled: false
        #   ingress:
        #     enabled: false
        #     # hosts:
        #     #   - host: code.example.com
        #     #     paths:
        #     #       - path: /
        #     # tls:
        #     #   - secretName: code.example.com-tls
        #     #     hosts:
        #     #       - code.example.com
        #   args:
        #     - --auth
        #     - "none"
        #     - --user-data-dir
        #     - "/config/.vscode"
        #     - --extensions-dir
        #     - "/config/.vscode"
        #     - --port
        #     - "8081"
        #     - "/config"
        #   args:
        #     - --auth=none
        #     - --user-data-dir=
        #   # @ignored
        #   volumeMounts:
        #     - name: config
        #       mountPath: /data/config

# -- environment variables.
env:
  # -- Set the container timezone
  TZ: UTC

# -- Configures service settings for the chart.
service:
  main:
    ports:
      http:
        port: 8123

ingress:
  # Ingress for the main application
  main:
    enabled: true
    # ingressClassName: "external-nginx"
    # annotations: {}
    hosts:
      - host: &host "hass.example.local"
        paths:
          - path: /
            pathType: Prefix
            service:
              name: main
              port: http
    tls:
      - hosts:
          - *host

  #  Ingress for code-server sidecar
  code:
    enabled: true
    # ingressClassName: "internal-nginx"
    hosts:
      - host: &host-code "hass-code.example.local"
        paths:
          - path: /
            pathType: Prefix
            service:
              name: code
              port: http
    tls:
      - hosts:
          - *host-code

persistence:
  # -- Configure persistence settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  config:
    enabled: true
    retain: false
    # storageClass: ""
    # accessMode: ReadWriteOnce
    # size: 1Gi

  # Configure an NFS mount to store backups on
  # backup:
  #   enabled: true
  #   type: nfs-csi
  #   server: nas.example.lan
  #   path: /volume/Backups/k8s/hass
  #   globalMounts:
  #     - path: /config/backups
